Fail pipeline if test results file is missing
This will make sure that the pipeline will not report success if for
some reason the test results file is not generated.

Issue #580

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -44,6 +44,14 @@ stages:
     - script: |
         docker create --name build-container build-image
         docker cp build-container:./app/CSharpFunctionalExtensions.Tests/TestResults ./testresults
+
+        # This will make sure that the pipeline fails if the tests were not executed for any reason
+        if [ ./testresults/testresults.trx ] && [ $(grep -E "<UnitTestResult" ./testresults/testresults.trx -c) -gt 0 ]; then
+          echo "Test results results found"
+        else
+          echo "No test results found"
+          exit 1
+        fi
       displayName: Extract test results
 
     - task: PublishTestResults@2
